name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build

    - name: Install Fantomas
      run: dotnet tool install fantomas-tool --global

    - name: Format check
      run: dotnet fantomas --check

    - name: Generate and build C code
      run: |
        # Generate C code from sample DBC with harness
        dotnet run --project src/Signal.CANdy.CLI -- -d examples/sample.dbc -o gen -t
        
        # Build the generated C code
        make -C gen build

    - name: Run C tests
      run: |
        # Run basic test suite
        ./gen/build/test_runner test_roundtrip
