/* Generated by Signal CANdy
   file_prefix=sc_, phys_type=float, phys_mode=double, dispatch=binary_search, motorola_start_bit=msb */

#ifndef MESSAGE_1_H
#define MESSAGE_1_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    float Signal_1;
    float Signal_2;
} MESSAGE_1_t;

bool MESSAGE_1_decode(MESSAGE_1_t* msg, const uint8_t data[], uint8_t dlc);
bool MESSAGE_1_encode(uint8_t data[], uint8_t* out_dlc, const MESSAGE_1_t* msg);

#ifdef __cplusplus
}
#endif

#endif // MESSAGE_1_H
