/* Generated by Signal CANdy
   file_prefix=sc_, phys_type=float, phys_mode=double, dispatch=binary_search, motorola_start_bit=msb */

#include "message_1.h"
#include "sc_utils.h"
#include <string.h>
#include <math.h>

bool MESSAGE_1_decode(MESSAGE_1_t* msg, const uint8_t data[], uint8_t dlc) {
    if (dlc < 8) { return false; }
    uint64_t raw_Signal_1 = 0;
    // Signal_1: start=0 len=8 factor=1 offset=0
    raw_Signal_1 = get_bits_le(data, 0, 8);
    msg->Signal_1 = (float)((double)raw_Signal_1 * 1 + 0);
    if (msg->Signal_1 < 0 || msg->Signal_1 > 255) { return false; }

    uint64_t raw_Signal_2 = 0;
    // Signal_2: start=8 len=16 factor=0.10000000000000001 offset=0
    raw_Signal_2 = get_bits_le(data, 8, 16);
    msg->Signal_2 = (float)((double)raw_Signal_2 * 0.10000000000000001 + 0);
    if (msg->Signal_2 < 0 || msg->Signal_2 > 100) { return false; }
    return true;
}

bool MESSAGE_1_encode(uint8_t data[], uint8_t* out_dlc, const MESSAGE_1_t* msg) {
    memset(data, 0, 8);
    *out_dlc = 8;
    if (msg->Signal_1 < 0 || msg->Signal_1 > 255) { return false; }
    double tmp_Signal_1 = ((double)msg->Signal_1 - 0) / 1;
    int64_t raw_Signal_1 = (int64_t)(tmp_Signal_1 >= 0 ? tmp_Signal_1 + 0.5 : tmp_Signal_1 - 0.5);
    set_bits_le(data, 0, 8, (uint64_t)raw_Signal_1);

    if (msg->Signal_2 < 0 || msg->Signal_2 > 100) { return false; }
    double tmp_Signal_2 = ((double)msg->Signal_2 - 0) / 0.10000000000000001;
    int64_t raw_Signal_2 = (int64_t)(tmp_Signal_2 >= 0 ? tmp_Signal_2 + 0.5 : tmp_Signal_2 - 0.5);
    set_bits_le(data, 8, 16, (uint64_t)raw_Signal_2);
    return true;
}
