/* Generated by Signal CANdy
   file_prefix=sc_, phys_type=float, phys_mode=double, dispatch=binary_search, motorola_start_bit=msb */

#ifndef MUX65_MSG_H
#define MUX65_MSG_H

#include <stdint.h>
#include <stdbool.h>
#include "sc_utils.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum { 
    MUX65_MSG_MUX_0 = 0,
    MUX65_MSG_MUX_1 = 1,
    MUX65_MSG_MUX_2 = 2,
    MUX65_MSG_MUX_3 = 3,
    MUX65_MSG_MUX_4 = 4,
    MUX65_MSG_MUX_5 = 5,
    MUX65_MSG_MUX_6 = 6,
    MUX65_MSG_MUX_7 = 7,
    MUX65_MSG_MUX_8 = 8,
    MUX65_MSG_MUX_9 = 9,
    MUX65_MSG_MUX_10 = 10,
    MUX65_MSG_MUX_11 = 11,
    MUX65_MSG_MUX_12 = 12,
    MUX65_MSG_MUX_13 = 13,
    MUX65_MSG_MUX_14 = 14,
    MUX65_MSG_MUX_15 = 15,
    MUX65_MSG_MUX_16 = 16,
    MUX65_MSG_MUX_17 = 17,
    MUX65_MSG_MUX_18 = 18,
    MUX65_MSG_MUX_19 = 19,
    MUX65_MSG_MUX_20 = 20,
    MUX65_MSG_MUX_21 = 21,
    MUX65_MSG_MUX_22 = 22,
    MUX65_MSG_MUX_23 = 23,
    MUX65_MSG_MUX_24 = 24,
    MUX65_MSG_MUX_25 = 25,
    MUX65_MSG_MUX_26 = 26,
    MUX65_MSG_MUX_27 = 27,
    MUX65_MSG_MUX_28 = 28,
    MUX65_MSG_MUX_29 = 29,
    MUX65_MSG_MUX_30 = 30,
    MUX65_MSG_MUX_31 = 31,
    MUX65_MSG_MUX_32 = 32,
    MUX65_MSG_MUX_33 = 33,
    MUX65_MSG_MUX_34 = 34,
    MUX65_MSG_MUX_35 = 35,
    MUX65_MSG_MUX_36 = 36,
    MUX65_MSG_MUX_37 = 37,
    MUX65_MSG_MUX_38 = 38,
    MUX65_MSG_MUX_39 = 39,
    MUX65_MSG_MUX_40 = 40,
    MUX65_MSG_MUX_41 = 41,
    MUX65_MSG_MUX_42 = 42,
    MUX65_MSG_MUX_43 = 43,
    MUX65_MSG_MUX_44 = 44,
    MUX65_MSG_MUX_45 = 45,
    MUX65_MSG_MUX_46 = 46,
    MUX65_MSG_MUX_47 = 47,
    MUX65_MSG_MUX_48 = 48,
    MUX65_MSG_MUX_49 = 49,
    MUX65_MSG_MUX_50 = 50,
    MUX65_MSG_MUX_51 = 51,
    MUX65_MSG_MUX_52 = 52,
    MUX65_MSG_MUX_53 = 53,
    MUX65_MSG_MUX_54 = 54,
    MUX65_MSG_MUX_55 = 55,
    MUX65_MSG_MUX_56 = 56,
    MUX65_MSG_MUX_57 = 57,
    MUX65_MSG_MUX_58 = 58,
    MUX65_MSG_MUX_59 = 59,
    MUX65_MSG_MUX_60 = 60,
    MUX65_MSG_MUX_61 = 61,
    MUX65_MSG_MUX_62 = 62,
    MUX65_MSG_MUX_63 = 63
} MUX65_MSG_mux_e;

#define MUX65_MSG_VALID_MUXSEL 0
#define MUX65_MSG_VALID_BRANCH_0 1
#define MUX65_MSG_VALID_BRANCH_1 2
#define MUX65_MSG_VALID_BRANCH_2 3
#define MUX65_MSG_VALID_BRANCH_3 4
#define MUX65_MSG_VALID_BRANCH_4 5
#define MUX65_MSG_VALID_BRANCH_5 6
#define MUX65_MSG_VALID_BRANCH_6 7
#define MUX65_MSG_VALID_BRANCH_7 8
#define MUX65_MSG_VALID_BRANCH_8 9
#define MUX65_MSG_VALID_BRANCH_9 10
#define MUX65_MSG_VALID_BRANCH_10 11
#define MUX65_MSG_VALID_BRANCH_11 12
#define MUX65_MSG_VALID_BRANCH_12 13
#define MUX65_MSG_VALID_BRANCH_13 14
#define MUX65_MSG_VALID_BRANCH_14 15
#define MUX65_MSG_VALID_BRANCH_15 16
#define MUX65_MSG_VALID_BRANCH_16 17
#define MUX65_MSG_VALID_BRANCH_17 18
#define MUX65_MSG_VALID_BRANCH_18 19
#define MUX65_MSG_VALID_BRANCH_19 20
#define MUX65_MSG_VALID_BRANCH_20 21
#define MUX65_MSG_VALID_BRANCH_21 22
#define MUX65_MSG_VALID_BRANCH_22 23
#define MUX65_MSG_VALID_BRANCH_23 24
#define MUX65_MSG_VALID_BRANCH_24 25
#define MUX65_MSG_VALID_BRANCH_25 26
#define MUX65_MSG_VALID_BRANCH_26 27
#define MUX65_MSG_VALID_BRANCH_27 28
#define MUX65_MSG_VALID_BRANCH_28 29
#define MUX65_MSG_VALID_BRANCH_29 30
#define MUX65_MSG_VALID_BRANCH_30 31
#define MUX65_MSG_VALID_BRANCH_31 32
#define MUX65_MSG_VALID_BRANCH_32 33
#define MUX65_MSG_VALID_BRANCH_33 34
#define MUX65_MSG_VALID_BRANCH_34 35
#define MUX65_MSG_VALID_BRANCH_35 36
#define MUX65_MSG_VALID_BRANCH_36 37
#define MUX65_MSG_VALID_BRANCH_37 38
#define MUX65_MSG_VALID_BRANCH_38 39
#define MUX65_MSG_VALID_BRANCH_39 40
#define MUX65_MSG_VALID_BRANCH_40 41
#define MUX65_MSG_VALID_BRANCH_41 42
#define MUX65_MSG_VALID_BRANCH_42 43
#define MUX65_MSG_VALID_BRANCH_43 44
#define MUX65_MSG_VALID_BRANCH_44 45
#define MUX65_MSG_VALID_BRANCH_45 46
#define MUX65_MSG_VALID_BRANCH_46 47
#define MUX65_MSG_VALID_BRANCH_47 48
#define MUX65_MSG_VALID_BRANCH_48 49
#define MUX65_MSG_VALID_BRANCH_49 50
#define MUX65_MSG_VALID_BRANCH_50 51
#define MUX65_MSG_VALID_BRANCH_51 52
#define MUX65_MSG_VALID_BRANCH_52 53
#define MUX65_MSG_VALID_BRANCH_53 54
#define MUX65_MSG_VALID_BRANCH_54 55
#define MUX65_MSG_VALID_BRANCH_55 56
#define MUX65_MSG_VALID_BRANCH_56 57
#define MUX65_MSG_VALID_BRANCH_57 58
#define MUX65_MSG_VALID_BRANCH_58 59
#define MUX65_MSG_VALID_BRANCH_59 60
#define MUX65_MSG_VALID_BRANCH_60 61
#define MUX65_MSG_VALID_BRANCH_61 62
#define MUX65_MSG_VALID_BRANCH_62 63
#define MUX65_MSG_VALID_BRANCH_63 64

#define MUX65_MSG_VALID_BYTES 9

typedef struct {
    float MuxSel;
    float Branch_0;
    float Branch_1;
    float Branch_2;
    float Branch_3;
    float Branch_4;
    float Branch_5;
    float Branch_6;
    float Branch_7;
    float Branch_8;
    float Branch_9;
    float Branch_10;
    float Branch_11;
    float Branch_12;
    float Branch_13;
    float Branch_14;
    float Branch_15;
    float Branch_16;
    float Branch_17;
    float Branch_18;
    float Branch_19;
    float Branch_20;
    float Branch_21;
    float Branch_22;
    float Branch_23;
    float Branch_24;
    float Branch_25;
    float Branch_26;
    float Branch_27;
    float Branch_28;
    float Branch_29;
    float Branch_30;
    float Branch_31;
    float Branch_32;
    float Branch_33;
    float Branch_34;
    float Branch_35;
    float Branch_36;
    float Branch_37;
    float Branch_38;
    float Branch_39;
    float Branch_40;
    float Branch_41;
    float Branch_42;
    float Branch_43;
    float Branch_44;
    float Branch_45;
    float Branch_46;
    float Branch_47;
    float Branch_48;
    float Branch_49;
    float Branch_50;
    float Branch_51;
    float Branch_52;
    float Branch_53;
    float Branch_54;
    float Branch_55;
    float Branch_56;
    float Branch_57;
    float Branch_58;
    float Branch_59;
    float Branch_60;
    float Branch_61;
    float Branch_62;
    float Branch_63;
    uint8_t valid[9];
    MUX65_MSG_mux_e mux_active;
} MUX65_MSG_t;

bool MUX65_MSG_decode(MUX65_MSG_t* msg, const uint8_t data[], uint8_t dlc);
bool MUX65_MSG_encode(uint8_t data[], uint8_t* out_dlc, const MUX65_MSG_t* msg);

#ifdef __cplusplus
}
#endif

#endif // MUX65_MSG_H
