/* Generated by Signal CANdy
   file_prefix=sc_, phys_type=float, phys_mode=double, dispatch=binary_search, motorola_start_bit=msb */

#include "mux_msg.h"
#include "sc_utils.h"
#include <string.h>
#include <math.h>

bool MUX_MSG_decode(MUX_MSG_t* msg, const uint8_t data[], uint8_t dlc) {
    if (dlc < 8) { return false; }
    msg->valid = 0u;

    uint64_t raw_MuxSwitch = 0;
    // MuxSwitch: start=0 len=4 factor=1 offset=0
    raw_MuxSwitch = get_bits_le(data, 0, 4);
    msg->MuxSwitch = (float)((double)raw_MuxSwitch * 1 + 0);
    if (msg->MuxSwitch < 0 || msg->MuxSwitch > 3) { return false; }
    msg->valid |= MUX_MSG_VALID_MUXSWITCH;
    msg->mux_active = (MUX_MSG_mux_e)((int)raw_MuxSwitch);

    uint64_t raw_Base_8 = 0;
    // Base_8: start=8 len=8 factor=1 offset=0
    raw_Base_8 = get_bits_le(data, 8, 8);
    msg->Base_8 = (float)((double)raw_Base_8 * 1 + 0);
    if (msg->Base_8 < 0 || msg->Base_8 > 255) { return false; }
    msg->valid |= MUX_MSG_VALID_BASE_8;

    if ((int)raw_MuxSwitch == 1) {
    uint64_t raw_Sig_m1 = 0;
    // Sig_m1: start=16 len=8 factor=1 offset=0
    raw_Sig_m1 = get_bits_le(data, 16, 8);
    msg->Sig_m1 = (float)((double)raw_Sig_m1 * 1 + 0);
    if (msg->Sig_m1 < 0 || msg->Sig_m1 > 255) { return false; }
    msg->valid |= MUX_MSG_VALID_SIG_M1;
    }
    if ((int)raw_MuxSwitch == 2) {
    uint64_t raw_Sig_m2 = 0;
    // Sig_m2: start=16 len=16 factor=1 offset=0
    raw_Sig_m2 = get_bits_le(data, 16, 16);
    msg->Sig_m2 = (float)((double)raw_Sig_m2 * 1 + 0);
    if (msg->Sig_m2 < 0 || msg->Sig_m2 > 65535) { return false; }
    msg->valid |= MUX_MSG_VALID_SIG_M2;
    }
    return true;
}

bool MUX_MSG_encode(uint8_t data[], uint8_t* out_dlc, const MUX_MSG_t* msg) {
    memset(data, 0, 8);
    *out_dlc = 8;
    if (msg->MuxSwitch < 0 || msg->MuxSwitch > 3) { return false; }

    double tmp_MuxSwitch = ((double)msg->MuxSwitch - 0) / 1;
    int64_t raw_MuxSwitch = (int64_t)(tmp_MuxSwitch >= 0 ? tmp_MuxSwitch + 0.5 : tmp_MuxSwitch - 0.5);

    set_bits_le(data, 0, 4, (uint64_t)raw_MuxSwitch);

    if (msg->Base_8 < 0 || msg->Base_8 > 255) { return false; }
    double tmp_Base_8 = ((double)msg->Base_8 - 0) / 1;
    int64_t raw_Base_8 = (int64_t)(tmp_Base_8 >= 0 ? tmp_Base_8 + 0.5 : tmp_Base_8 - 0.5);
    set_bits_le(data, 8, 8, (uint64_t)raw_Base_8);

    if ((int)raw_MuxSwitch == 1) {
    if (msg->Sig_m1 < 0 || msg->Sig_m1 > 255) { return false; }
    double tmp_Sig_m1 = ((double)msg->Sig_m1 - 0) / 1;
    int64_t raw_Sig_m1 = (int64_t)(tmp_Sig_m1 >= 0 ? tmp_Sig_m1 + 0.5 : tmp_Sig_m1 - 0.5);
    set_bits_le(data, 16, 8, (uint64_t)raw_Sig_m1);
    }
    if ((int)raw_MuxSwitch == 2) {
    if (msg->Sig_m2 < 0 || msg->Sig_m2 > 65535) { return false; }
    double tmp_Sig_m2 = ((double)msg->Sig_m2 - 0) / 1;
    int64_t raw_Sig_m2 = (int64_t)(tmp_Sig_m2 >= 0 ? tmp_Sig_m2 + 0.5 : tmp_Sig_m2 - 0.5);
    set_bits_le(data, 16, 16, (uint64_t)raw_Sig_m2);
    }
    return true;
}
