/* Generated by Signal CANdy
   file_prefix=sc_, phys_type=float, phys_mode=double, dispatch=binary_search, motorola_start_bit=msb */

#ifndef MUX_MSG_H
#define MUX_MSG_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum { 
    MUX_MSG_MUX_1 = 1,
    MUX_MSG_MUX_2 = 2
} MUX_MSG_mux_e;

#define MUX_MSG_VALID_MUXSWITCH (1u << 0)
#define MUX_MSG_VALID_BASE_8 (1u << 1)
#define MUX_MSG_VALID_SIG_M1 (1u << 2)
#define MUX_MSG_VALID_SIG_M2 (1u << 3)

typedef struct {
    float MuxSwitch;
    float Base_8;
    float Sig_m1;
    float Sig_m2;
    uint32_t valid;
    MUX_MSG_mux_e mux_active;
} MUX_MSG_t;

bool MUX_MSG_decode(MUX_MSG_t* msg, const uint8_t data[], uint8_t dlc);
bool MUX_MSG_encode(uint8_t data[], uint8_t* out_dlc, const MUX_MSG_t* msg);

#ifdef __cplusplus
}
#endif

#endif // MUX_MSG_H
