/* Generated by Signal CANdy
   file_prefix=sc_, phys_type=float, phys_mode=double, dispatch=binary_search, motorola_start_bit=msb */
#include <stdint.h>
#include <stdbool.h>
#include "sc_registry.h"
#include "message_1.h"

typedef bool (*decode_func_t)(void* msg, const uint8_t data[], uint8_t dlc);

typedef struct { uint32_t id; decode_func_t func; } decoder_entry_t;

static const decoder_entry_t decoders[] = {
    { 100u, (decode_func_t)MESSAGE_1_decode }
};
bool decode_message(uint32_t id, const uint8_t data[], uint8_t dlc, void* msg) {
    int low = 0;
    int high = (int)(sizeof(decoders) / sizeof(decoder_entry_t)) - 1;
    while (low <= high) {
        int mid = low + (high - low) / 2;
        if (decoders[mid].id == id) {
            return decoders[mid].func(msg, data, dlc);
        }
        if (decoders[mid].id < id) low = mid + 1; else high = mid - 1;
    }
    return false;
}
