/* Generated by Signal CANdy
   file_prefix=sc_, phys_type=float, phys_mode=double, dispatch=binary_search, motorola_start_bit=msb */
#ifndef SC_REGISTRY_H
#define SC_REGISTRY_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

bool decode_message(uint32_t id, const uint8_t data[], uint8_t dlc, void* msg);

#ifdef __cplusplus
}
#endif

#endif // SC_REGISTRY_H
