/* Generated by Signal CANdy
   file_prefix=sc_, phys_type=float, phys_mode=double, dispatch=binary_search, motorola_start_bit=msb */
#include "sc_utils.h"

/* CAN FD DLC to payload length mapping (ISO 11898-1) */
static const uint8_t CANFD_DLC_TO_LEN[16] = { 0,1,2,3,4,5,6,7,8,12,16,20,24,32,48,64 };

uint8_t canfd_dlc_to_len(uint8_t dlc) {
    if (dlc > 15) dlc = 15;
    return CANFD_DLC_TO_LEN[dlc];
}

uint8_t canfd_len_to_dlc(uint8_t len) {
    if (len <= 8) return (uint8_t)len;
    if (len <= 12) return 9;
    if (len <= 16) return 10;
    if (len <= 20) return 11;
    if (len <= 24) return 12;
    if (len <= 32) return 13;
    if (len <= 48) return 14;
    return 15;
}

// Little-endian bit extraction (supports CAN FD up to 64 bytes)
uint64_t get_bits_le(const uint8_t* data, uint16_t start_bit, uint16_t length) {
    uint64_t value = 0;
    uint16_t byte_offset = start_bit / 8;
    uint16_t bit_offset = start_bit % 8;
    uint16_t n_bytes = (bit_offset + length + 7) / 8;
    for (uint16_t i = 0; i < n_bytes; ++i) {
        value |= (uint64_t)data[byte_offset + i] << (i * 8);
    }
    value >>= bit_offset;
    value &= (length == 64) ? UINT64_MAX : ((1ULL << length) - 1);
    return value;
}

// Little-endian bit insertion (supports CAN FD up to 64 bytes)
void set_bits_le(uint8_t* data, uint16_t start_bit, uint16_t length, uint64_t value) {
    uint16_t byte_offset = start_bit / 8;
    uint16_t bit_offset = start_bit % 8;
    uint64_t mask = (length == 64) ? UINT64_MAX : ((1ULL << length) - 1);
    uint64_t clear_mask = mask << bit_offset;
    uint16_t n_bytes = (bit_offset + length + 7) / 8;
    for (uint16_t i = 0; i < n_bytes; ++i) {
        data[byte_offset + i] &= ~(uint8_t)(clear_mask >> (i * 8));
    }
    uint64_t insert_value = (value & mask) << bit_offset;
    for (uint16_t i = 0; i < n_bytes; ++i) {
        data[byte_offset + i] |= (uint8_t)(insert_value >> (i * 8));
    }
}

// Big-endian (Motorola) bit extraction (DBC semantics, sawtooth)
uint64_t get_bits_be(const uint8_t* data, uint16_t start_bit, uint16_t length) {
    uint64_t value = 0;
    int byte = start_bit / 8;
    int bit = start_bit % 8; // 7..0 within byte, 7 is MSB
    for (uint16_t i = 0; i < length; ++i) {
        int curByte = byte;
        int curBit = bit - (int)i;
        while (curBit < 0) { curBit += 8; ++curByte; } // move to next higher byte
        uint8_t b = data[curByte];
        uint8_t bitval = (uint8_t)((b >> curBit) & 1u);
        value = (value << 1) | bitval; // assemble MSB-first
    }
    return value;
}

// Big-endian (Motorola) bit insertion (DBC semantics, sawtooth)
void set_bits_be(uint8_t* data, uint16_t start_bit, uint16_t length, uint64_t value) {
    int byte = start_bit / 8;
    int bit = start_bit % 8;
    for (uint16_t i = 0; i < length; ++i) {
        int curByte = byte;
        int curBit = bit - (int)i;
        while (curBit < 0) { curBit += 8; ++curByte; } // move to next higher byte
        uint8_t bitval = (uint8_t)((value >> (length - 1 - i)) & 1u); // MSB-first
        data[curByte] = (uint8_t)((data[curByte] & (uint8_t)~(1u << curBit)) | (uint8_t)(bitval << curBit));
    }
}
