/* Generated by Signal CANdy
   file_prefix=sc_, phys_type=float, phys_mode=double, dispatch=binary_search, motorola_start_bit=msb */
#ifndef SC_UTILS_H
#define SC_UTILS_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

// Little-endian bit extraction functions
uint64_t get_bits_le(const uint8_t* data, uint16_t start_bit, uint16_t length);

// Little-endian bit insertion functions
void set_bits_le(uint8_t* data, uint16_t start_bit, uint16_t length, uint64_t value);

// Big-endian (Motorola) bit extraction
uint64_t get_bits_be(const uint8_t* data, uint16_t start_bit, uint16_t length);

// Big-endian (Motorola) bit insertion
void set_bits_be(uint8_t* data, uint16_t start_bit, uint16_t length, uint64_t value);

// CAN FD DLC <-> length mapping
uint8_t canfd_dlc_to_len(uint8_t dlc);
uint8_t canfd_len_to_dlc(uint8_t len);

#ifdef __cplusplus
}
#endif

#endif // SC_UTILS_H
