/* Generated by Signal CANdy
   file_prefix=sc_, phys_type=float, phys_mode=double, dispatch=binary_search, motorola_start_bit=msb */

#ifndef VT_MSG_H
#define VT_MSG_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    VT_MSG_MODE_OFF = 0,
    VT_MSG_MODE_ON = 1,
    VT_MSG_MODE_AUTO = 2,
} VT_MSG_Mode_e;

const char* VT_MSG_Mode_to_string(int v);

typedef enum {
    VT_MSG_STATE_IDLE = 0,
    VT_MSG_STATE_RUN = 1,
    VT_MSG_STATE_STOP = 2,
} VT_MSG_State_e;

const char* VT_MSG_State_to_string(int v);

typedef enum {
    VT_MSG_ERROR_OK = 0,
    VT_MSG_ERROR_WARN = 1,
    VT_MSG_ERROR_FAIL = 2,
} VT_MSG_Error_e;

const char* VT_MSG_Error_to_string(int v);

typedef enum { 
    VT_MSG_MUX_0 = 0,
    VT_MSG_MUX_1 = 1
} VT_MSG_mux_e;

#define VT_MSG_VALID_MODE (1u << 0)
#define VT_MSG_VALID_BASE (1u << 1)
#define VT_MSG_VALID_STATE (1u << 2)
#define VT_MSG_VALID_ERROR (1u << 3)

typedef struct {
    float Mode;
    float Base;
    float State;
    float Error;
    uint32_t valid;
    VT_MSG_mux_e mux_active;
} VT_MSG_t;

bool VT_MSG_decode(VT_MSG_t* msg, const uint8_t data[], uint8_t dlc);
bool VT_MSG_encode(uint8_t data[], uint8_t* out_dlc, const VT_MSG_t* msg);

#ifdef __cplusplus
}
#endif

#endif // VT_MSG_H
