/* Generated by Signal CANdy
   file_prefix=sc_, phys_type=float, phys_mode=double, dispatch=binary_search, motorola_start_bit=msb */

#include "vt_msg.h"
#include "sc_utils.h"
#include <string.h>
#include <math.h>

const char* VT_MSG_Mode_to_string(int v) {
    switch (v) {
    case 0: return "OFF";
    case 1: return "ON";
    case 2: return "AUTO";
    default: return "UNKNOWN";
    }
}

const char* VT_MSG_State_to_string(int v) {
    switch (v) {
    case 0: return "IDLE";
    case 1: return "RUN";
    case 2: return "STOP";
    default: return "UNKNOWN";
    }
}

const char* VT_MSG_Error_to_string(int v) {
    switch (v) {
    case 0: return "OK";
    case 1: return "WARN";
    case 2: return "FAIL";
    default: return "UNKNOWN";
    }
}

bool VT_MSG_decode(VT_MSG_t* msg, const uint8_t data[], uint8_t dlc) {
    if (dlc < 8) { return false; }
    msg->valid = 0u;

    uint64_t raw_Mode = 0;
    // Mode: start=0 len=8 factor=1 offset=0
    raw_Mode = get_bits_le(data, 0, 8);
    msg->Mode = (float)((double)raw_Mode * 1 + 0);
    if (msg->Mode < 0 || msg->Mode > 255) { return false; }
    msg->valid |= VT_MSG_VALID_MODE;
    msg->mux_active = (VT_MSG_mux_e)((int)raw_Mode);

    uint64_t raw_Base = 0;
    // Base: start=8 len=8 factor=1 offset=0
    raw_Base = get_bits_le(data, 8, 8);
    msg->Base = (float)((double)raw_Base * 1 + 0);
    if (msg->Base < 0 || msg->Base > 255) { return false; }
    msg->valid |= VT_MSG_VALID_BASE;

    if ((int)raw_Mode == 0) {
    uint64_t raw_State = 0;
    // State: start=16 len=8 factor=1 offset=0
    raw_State = get_bits_le(data, 16, 8);
    msg->State = (float)((double)raw_State * 1 + 0);
    if (msg->State < 0 || msg->State > 255) { return false; }
    msg->valid |= VT_MSG_VALID_STATE;
    }
    if ((int)raw_Mode == 1) {
    uint64_t raw_Error = 0;
    // Error: start=24 len=8 factor=1 offset=0
    raw_Error = get_bits_le(data, 24, 8);
    msg->Error = (float)((double)raw_Error * 1 + 0);
    if (msg->Error < 0 || msg->Error > 255) { return false; }
    msg->valid |= VT_MSG_VALID_ERROR;
    }
    return true;
}

bool VT_MSG_encode(uint8_t data[], uint8_t* out_dlc, const VT_MSG_t* msg) {
    memset(data, 0, 8);
    *out_dlc = 8;
    if (msg->Mode < 0 || msg->Mode > 255) { return false; }

    double tmp_Mode = ((double)msg->Mode - 0) / 1;
    int64_t raw_Mode = (int64_t)(tmp_Mode >= 0 ? tmp_Mode + 0.5 : tmp_Mode - 0.5);

    set_bits_le(data, 0, 8, (uint64_t)raw_Mode);

    if (msg->Base < 0 || msg->Base > 255) { return false; }
    double tmp_Base = ((double)msg->Base - 0) / 1;
    int64_t raw_Base = (int64_t)(tmp_Base >= 0 ? tmp_Base + 0.5 : tmp_Base - 0.5);
    set_bits_le(data, 8, 8, (uint64_t)raw_Base);

    if ((int)raw_Mode == 0) {
    if (msg->State < 0 || msg->State > 255) { return false; }
    double tmp_State = ((double)msg->State - 0) / 1;
    int64_t raw_State = (int64_t)(tmp_State >= 0 ? tmp_State + 0.5 : tmp_State - 0.5);
    set_bits_le(data, 16, 8, (uint64_t)raw_State);
    }
    if ((int)raw_Mode == 1) {
    if (msg->Error < 0 || msg->Error > 255) { return false; }
    double tmp_Error = ((double)msg->Error - 0) / 1;
    int64_t raw_Error = (int64_t)(tmp_Error >= 0 ? tmp_Error + 0.5 : tmp_Error - 0.5);
    set_bits_le(data, 24, 8, (uint64_t)raw_Error);
    }
    return true;
}
