namespace Signal.CANdy.Core

open System
open System.IO
open System.Security.Cryptography
open System.Text
open System.Text.RegularExpressions

module ArtifactWriter =

    type ArtifactKind =
        | Image
        | Header
        | Inspect

    type Artifact =
        { Kind: ArtifactKind
          Destination: string
          Content: byte array }

    type ArtifactError = ArtifactError of string

    type IArtifactFileSystem =
        abstract FileExists: string -> bool
        abstract DirectoryExists: string -> bool
        abstract CreateDirectory: string -> unit
        abstract CreateNew: string -> Stream
        abstract Move: string * string -> unit
        abstract DeleteFile: string -> unit
        abstract DeleteDirectory: string -> unit

    type private RealFileSystem() =
        interface IArtifactFileSystem with
            member _.FileExists path = File.Exists path
            member _.DirectoryExists path = Directory.Exists path

            member _.CreateDirectory path =
                Directory.CreateDirectory(path) |> ignore

            member _.CreateNew path =
                new FileStream(path, FileMode.CreateNew, FileAccess.Write, FileShare.None) :> Stream

            member _.Move(source, destination) = File.Move(source, destination)

            member _.DeleteFile path =
                if File.Exists path then
                    File.Delete path

            member _.DeleteDirectory path =
                if Directory.Exists path then
                    Directory.Delete path

    let private stemSymbols (imagePath: string) =
        let stem = Path.GetFileNameWithoutExtension(imagePath)

        if String.IsNullOrEmpty stem || stem |> Seq.exists (fun c -> int c > 127) then
            None
        else
            let parts =
                Regex.Split(stem, "[^A-Za-z0-9]+") |> Array.filter (String.IsNullOrEmpty >> not)

            if parts.Length = 0 || not (Char.IsLetter parts.[0].[0]) then
                None
            else
                let upper = parts |> String.concat "_" |> _.ToUpperInvariant()

                let pascal =
                    parts
                    |> Array.map (fun part -> Char.ToUpperInvariant(part.[0]).ToString() + part.Substring(1))
                    |> String.concat ""

                Some("SCIMG_" + upper, "Scimg" + pascal)

    let renderHeader (projectName: string) (imagePath: string) (bytes: byte array) =
        match stemSymbols imagePath with
        | None -> Error[ArtifactError "Image filename stem cannot form a C identifier."]
        | Some(upper, pascal) ->
            let hash = SHA256.HashData(bytes) |> Convert.ToHexString |> _.ToLowerInvariant()
            let builder = StringBuilder()

            builder
                .Append("/*\n * Generated by Signal.CANdy.CLI project build.\n * Project: ")
                .Append(projectName)
                .Append("\n * Image SHA-256: ")
                .Append(hash)
                .Append("\n */\n")
            |> ignore

            builder
                .Append("#ifndef G")
                .Append(upper)
                .Append("_H\n#define G")
                .Append(upper)
                .Append("_H\n\n#include <stdint.h>\n\n")
            |> ignore

            builder.Append("#define G").Append(upper).Append("_BYTE_COUNT ").Append(bytes.Length).Append("u\n\n")
            |> ignore

            builder
                .Append("const uint8_t g")
                .Append(pascal)
                .Append("Bytes[G")
                .Append(upper)
                .Append("_BYTE_COUNT] = {\n")
            |> ignore

            for index in 0 .. bytes.Length - 1 do
                if index % 16 = 0 then
                    builder.Append("    ") |> ignore

                builder.AppendFormat("0x{0:X2},", bytes.[index]) |> ignore

                if index % 16 = 15 || index = bytes.Length - 1 then
                    builder.Append('\n') |> ignore
                else
                    builder.Append(' ') |> ignore

            builder.Append("};\n\n#endif /* G").Append(upper).Append("_H */\n") |> ignore
            Ok(Encoding.ASCII.GetBytes(builder.ToString()))

    let private rank (kind: ArtifactKind) =
        match kind with
        | Image -> 0
        | Header -> 1
        | Inspect -> 2

    let writeAtomicWith (fs: IArtifactFileSystem) (artifacts: Artifact list) =
        let ordered = artifacts |> List.sortBy (fun artifact -> rank artifact.Kind)
        let destinations = ordered |> List.map _.Destination

        let normalized =
            destinations |> List.map (fun (path: string) -> path.ToUpperInvariant())

        if normalized.Length <> (normalized |> List.distinct).Length then
            Error[ArtifactError "Artifact destinations collide."]
        elif
            destinations
            |> List.exists (fun path -> fs.FileExists(path) || fs.DirectoryExists(path))
        then
            Error[ArtifactError "An artifact destination already exists."]
        else
            let staged = ResizeArray<string * string>()
            let committed = ResizeArray<string>()
            let createdDirectories = ResizeArray<string>()

            try
                for artifact in ordered do
                    let directory = Path.GetDirectoryName artifact.Destination

                    if not (String.IsNullOrEmpty directory) && not (fs.DirectoryExists directory) then
                        fs.CreateDirectory directory
                        createdDirectories.Add directory

                    let temp =
                        Path.Combine(
                            directory,
                            "."
                            + Path.GetFileName(artifact.Destination)
                            + ".signal-candy-"
                            + string Environment.ProcessId
                            + "-"
                            + Guid.NewGuid().ToString("N")
                            + ".tmp"
                        )

                    use stream = fs.CreateNew temp
                    staged.Add(temp, artifact.Destination)
                    stream.Write(artifact.Content, 0, artifact.Content.Length)
                    stream.Flush()

                for temp, destination in staged do
                    fs.Move(temp, destination)
                    committed.Add destination

                Ok()
            with ex ->
                for temp, _ in staged do
                    try
                        fs.DeleteFile temp
                    with _ ->
                        ()

                for destination in committed do
                    try
                        fs.DeleteFile destination
                    with _ ->
                        ()

                for directory in Seq.rev createdDirectories do
                    try
                        fs.DeleteDirectory directory
                    with _ ->
                        ()

                Error[ArtifactError ex.Message]

    let writeAtomic artifacts =
        writeAtomicWith (RealFileSystem()) artifacts
