namespace Signal.CANdy.Core

open System
open System.IO
open System.Reflection
open Signal.CANdy.Core.Ir
open Signal.CANdy.Core.Errors
open Scriban
open Scriban.Runtime

module Codegen =

    exception TemplateRenderException of string

    module Templates =
        let private tryGetTemplateText (templateName: string) =
            let assembly = Assembly.GetExecutingAssembly()

            assembly.GetManifestResourceNames()
            |> Array.tryFind (fun name -> name.EndsWith(sprintf "templates.%s" templateName, StringComparison.Ordinal))
            |> Option.bind (fun resourceName ->
                use stream = assembly.GetManifestResourceStream(resourceName)

                if isNull stream then
                    None
                else
                    use reader = new StreamReader(stream)
                    Some(resourceName, reader.ReadToEnd()))

        let renderOrRaise (templateName: string) (model: (string * obj) list) =
            match tryGetTemplateText templateName with
            | None -> raise (TemplateRenderException(sprintf "Template not found: %s" templateName))
            | Some(path, text) ->
                let template = Template.Parse(text, path)

                if template.HasErrors then
                    let messages = template.Messages |> Seq.map string |> String.concat "; "

                    raise (TemplateRenderException(sprintf "Template parse failed for %s: %s" templateName messages))

                let context = TemplateContext()
                let scriptObject = ScriptObject()

                model |> List.iter (fun (name, value) -> scriptObject.Add(name, value))

                context.PushGlobal(scriptObject)
                template.Render(context)

    module Utils =
        // Build a macro-safe header guard from prefix + base name
        let private guard (prefix: string) (baseName: string) =
            let raw = (prefix + baseName).ToUpperInvariant()

            raw
            |> Seq.map (fun ch -> if Char.IsLetterOrDigit ch then ch else '_')
            |> Seq.toArray
            |> fun arr -> new string (arr)

        let utilsHeaderName (config: Signal.CANdy.Core.Config.Config) = sprintf "%sutils.h" config.FilePrefix
        let utilsSourceName (config: Signal.CANdy.Core.Config.Config) = sprintf "%sutils.c" config.FilePrefix

        type private UtilsHeaderTemplateModel =
            { banner: string
              header_guard: string
              get_bits_le_decl: string
              set_bits_le_decl: string
              get_bits_be_decl: string
              set_bits_be_decl: string
              canfd_dlc_to_len_decl: string
              canfd_len_to_dlc_decl: string }

        type private UtilsSourceTemplateModel =
            { banner: string
              utils_header_name: string }

        let private banner (config: Signal.CANdy.Core.Config.Config) =
            sprintf
                "/* Generated by Signal CANdy\n   file_prefix=%s, phys_type=%s, phys_mode=%s, dispatch=%s, motorola_start_bit=%s */\n"
                config.FilePrefix
                config.PhysType
                config.PhysMode
                config.Dispatch
                config.MotorolaStartBit

        let utilsHContent (config: Signal.CANdy.Core.Config.Config) (ir: Ir) =
            let hasCrcJ1850 =
                ir.Messages
                |> List.exists (fun msg ->
                    msg.Signals
                    |> List.exists (fun s ->
                        match s.CrcMeta with
                        | Some meta -> meta.Algorithm = CrcAlgorithmId.CRC8_SAE_J1850
                        | None -> false))

            let hasCrc8h2f =
                ir.Messages
                |> List.exists (fun msg ->
                    msg.Signals
                    |> List.exists (fun s ->
                        match s.CrcMeta with
                        | Some meta -> meta.Algorithm = CrcAlgorithmId.CRC8_8H2F
                        | None -> false))

            let model: (string * obj) list =
                [ "banner", box (banner config)
                  "header_guard", box (guard config.FilePrefix "utils_h")
                  "get_bits_le_decl",
                  box "uint64_t get_bits_le(const uint8_t* data, uint16_t start_bit, uint16_t length);"
                  "set_bits_le_decl",
                  box "void set_bits_le(uint8_t* data, uint16_t start_bit, uint16_t length, uint64_t value);"
                  "get_bits_be_decl",
                  box "uint64_t get_bits_be(const uint8_t* data, uint16_t start_bit, uint16_t length);"
                  "set_bits_be_decl",
                  box "void set_bits_be(uint8_t* data, uint16_t start_bit, uint16_t length, uint64_t value);"
                  "canfd_dlc_to_len_decl", box "uint8_t canfd_dlc_to_len(uint8_t dlc);"
                  "canfd_len_to_dlc_decl", box "uint8_t canfd_len_to_dlc(uint8_t len);"
                  "has_crc_j1850", box hasCrcJ1850
                  "has_crc_8h2f", box hasCrc8h2f ]

            Templates.renderOrRaise "utils.h.scriban" model

        let utilsCContent (config: Signal.CANdy.Core.Config.Config) (ir: Ir) =
            let hasCrcJ1850 =
                ir.Messages
                |> List.exists (fun msg ->
                    msg.Signals
                    |> List.exists (fun s ->
                        match s.CrcMeta with
                        | Some meta -> meta.Algorithm = CrcAlgorithmId.CRC8_SAE_J1850
                        | None -> false))

            let hasCrc8h2f =
                ir.Messages
                |> List.exists (fun msg ->
                    msg.Signals
                    |> List.exists (fun s ->
                        match s.CrcMeta with
                        | Some meta -> meta.Algorithm = CrcAlgorithmId.CRC8_8H2F
                        | None -> false))

            let model: (string * obj) list =
                [ "banner", box (banner config)
                  "utils_header_name", box (utilsHeaderName config)
                  "has_crc_j1850", box hasCrcJ1850
                  "has_crc_8h2f", box hasCrc8h2f ]

            Templates.renderOrRaise "utils.c.scriban" model

        // Helper to choose C accessor based on byte order
        let accessorNames (byteOrder: ByteOrder) =
            match byteOrder with
            | ByteOrder.Little -> ("get_bits_le", "set_bits_le")
            | ByteOrder.Big -> ("get_bits_be", "set_bits_be")

        // Convert Motorola (BE) start bit from LSB-convention to MSB-convention using sawtooth numbering.
        let internal motorolaMsbFromLsb (start: int) (length: int) : int =
            let steps = max 0 (length - 1)
            let mutable byteIdx = start / 8
            let mutable bitIdx = start % 8 // 0..7, where 7 is MSB

            for _ in 1..steps do
                if bitIdx < 7 then
                    bitIdx <- bitIdx + 1
                else
                    (byteIdx <- byteIdx - 1
                     bitIdx <- 0)

            byteIdx * 8 + bitIdx

        // Choose effective start bit depending on config for Motorola signals; LE stays unchanged.
        let chooseStartBit (signal: Signal) (config: Signal.CANdy.Core.Config.Config) : int =
            let start = int signal.StartBit
            let len = int signal.Length

            match signal.ByteOrder with
            | ByteOrder.Big ->
                match config.MotorolaStartBit.ToLowerInvariant() with
                | "lsb" -> motorolaMsbFromLsb start len
                | _ -> start // default "msb"
            | _ -> start

        // Detect if factor equals 10^-n within tolerance and return integer scale (10^n)
        let tryPowerOfTenScale (factor: float) : int64 option =
            if factor <= 0.0 then
                None
            else
                let eps = 1e-12

                let rec loop n =
                    if n > 9 then
                        None
                    else
                        let scaleF = pown 10.0 n

                        if abs (factor - (1.0 / scaleF)) < eps then
                            Some(int64 (pown 10 n))
                        else
                            loop (n + 1)

                loop 0

        /// Detect when DBC [min|max] fields store raw CAN counts instead of physical values.
        /// Returns true if the declared min/max range cannot contain the full physical range
        /// computed from factor, offset, and bit width - indicating raw-count sentinel usage.
        let isRawRangeSentinel
            (minV: float)
            (maxV: float)
            (factor: float)
            (offset: float)
            (length: uint16)
            (isSigned: bool)
            : bool =
            let bitLen = int length
            let unsignedRawMax = Math.Pow(2.0, float bitLen) - 1.0
            let signedHalf = Math.Pow(2.0, float (bitLen - 1))
            let signedRawMin = -signedHalf
            let signedRawMax = signedHalf - 1.0

            let rawMin, rawMax =
                if isSigned then
                    (signedRawMin, signedRawMax)
                else
                    (0.0, unsignedRawMax)

            let physMin = offset + factor * rawMin
            let physMax = offset + factor * rawMax
            let eps = 1e-9
            let physOutOfDeclaredRange = physMin < minV - eps || physMax > maxV + eps

            let matchesUnsignedRawCountRange =
                abs minV <= eps && abs (maxV - unsignedRawMax) <= eps

            let matchesSignedRawCountRange =
                isSigned && abs (minV - signedRawMin) <= eps && abs (maxV - signedRawMax) <= eps

            let matchesSignedUnsignedPhysicalRange =
                isSigned
                && abs (minV - offset) <= eps
                && abs (maxV - (offset + factor * unsignedRawMax)) <= eps

            physOutOfDeclaredRange
            && (matchesUnsignedRawCountRange
                || matchesSignedRawCountRange
                || matchesSignedUnsignedPhysicalRange)

    module Message =
        open Utils

        type private MessageHeaderTemplateModel =
            { banner: string
              header_guard: string
              signal_declarations_h: string
              pre_struct_declarations: string
              struct_extra_fields: string
              message_name: string }

        type private MessageSourceTemplateModel =
            { banner: string
              message_header_name: string
              utils_header_name: string
              value_table_definitions: string
              message_name: string
              message_length: int
              signal_decode_c: string
              signal_encode_c: string }

        // Sanitize a string to an uppercase C identifier (A-Z0-9_), prefix with N_ if starting with a digit or empty
        let private sanitizeEnumIdent (s: string) : string =
            let up = s.ToUpperInvariant()

            let mapped =
                up
                |> Seq.map (fun ch -> if Char.IsLetterOrDigit ch then ch else '_')
                |> Seq.toArray
                |> fun arr -> new string (arr)

            let trimmed =
                mapped.Trim([| '_' |])
                |> fun t -> if String.IsNullOrWhiteSpace t then "N" else t

            let start = trimmed.[0]

            if Char.IsDigit start then "N_" + trimmed else trimmed

        let private fieldDecl (s: Signal) = sprintf "    float %s;" s.Name

        let private genDecodeForSignal (s: Signal) (doRangeCheck: bool) (config: Signal.CANdy.Core.Config.Config) =
            let len = int s.Length
            let startEff = chooseStartBit s config
            let (getFn, _) = accessorNames s.ByteOrder
            let raw = sprintf "raw_%s" s.Name

            let signFix =
                if s.IsSigned then
                    sprintf "    if (%s & (1ULL << (%d - 1))) { %s |= ~((1ULL << %d) - 1); }" raw len raw len
                else
                    ""
            // For signed signals, cast uint64_t to int64_t before floating-point conversion
            // so that sign-extended values are interpreted correctly as negative numbers.
            let rawCast = if s.IsSigned then sprintf "(int64_t)%s" raw else raw

            let physAssignFloatDouble =
                sprintf "    msg->%s = (float)((double)%s * %.17g + %.17g);" s.Name rawCast s.Factor s.Offset

            let physAssignFloatFloat =
                sprintf
                    "    msg->%s = (float)(((float)%s * (float)%.17g) + (float)%.17g);"
                    s.Name
                    rawCast
                    s.Factor
                    s.Offset

            let physAssign =
                match config.PhysType.ToLowerInvariant() with
                | "fixed" ->
                    match Utils.tryPowerOfTenScale s.Factor with
                    | Some scale when abs (s.Offset - Math.Round(s.Offset)) < 1e-12 ->
                        sprintf
                            "    msg->%s = (float)(((double)%s + (%.0f)) / (double)%d);"
                            s.Name
                            rawCast
                            (Math.Round(s.Offset * (float scale)))
                            scale
                    | _ ->
                        (match config.PhysMode.ToLowerInvariant() with
                         | "fixed_float" -> physAssignFloatFloat
                         | _ -> physAssignFloatDouble)
                | _ ->
                    (match config.PhysMode.ToLowerInvariant() with
                     | "float" -> physAssignFloatFloat
                     | _ -> physAssignFloatDouble)

            let rangeCheck =
                if doRangeCheck then
                    match s.Minimum, s.Maximum with
                    | Some minV, Some maxV ->
                        if minV >= maxV then
                            None
                        elif Utils.isRawRangeSentinel minV maxV s.Factor s.Offset s.Length s.IsSigned then
                            None
                        else
                            Some(
                                sprintf
                                    "    if (msg->%s < %.17g || msg->%s > %.17g) { return false; }"
                                    s.Name
                                    minV
                                    s.Name
                                    maxV
                            )
                    | Some minV, None -> Some(sprintf "    if (msg->%s < %.17g) { return false; }" s.Name minV)
                    | None, Some maxV -> Some(sprintf "    if (msg->%s > %.17g) { return false; }" s.Name maxV)
                    | _ -> None
                else
                    None

            [ sprintf "    uint64_t %s = 0;" raw
              sprintf "    // %s: start=%d len=%d factor=%.17g offset=%.17g" s.Name startEff len s.Factor s.Offset
              sprintf "    %s = %s(data, %d, %d);" raw getFn startEff len
              if signFix <> "" then signFix else null
              physAssign
              match rangeCheck with
              | Some r -> r
              | None -> null ]
            |> List.choose (fun x -> if isNull (box x) then None else Some x)
            |> String.concat "\n"

        let private genEncodeForSignal (s: Signal) (doRangeCheck: bool) (config: Signal.CANdy.Core.Config.Config) =
            let len = int s.Length
            let startEff = chooseStartBit s config
            let (_, setFn) = accessorNames s.ByteOrder

            let rangeChecks =
                if doRangeCheck then
                    match s.Minimum, s.Maximum with
                    | Some minV, Some maxV ->
                        if minV >= maxV then
                            None
                        elif Utils.isRawRangeSentinel minV maxV s.Factor s.Offset s.Length s.IsSigned then
                            None
                        else
                            Some(
                                sprintf
                                    "    if (msg->%s < %.17g || msg->%s > %.17g) { return false; }"
                                    s.Name
                                    minV
                                    s.Name
                                    maxV
                            )
                    | Some minV, None -> Some(sprintf "    if (msg->%s < %.17g) { return false; }" s.Name minV)
                    | None, Some maxV -> Some(sprintf "    if (msg->%s > %.17g) { return false; }" s.Name maxV)
                    | _ -> None
                else
                    None

            let computeRawDouble =
                sprintf
                    "    double tmp_%s = ((double)msg->%s - %.17g) / %.17g;\n    int64_t raw_%s = (int64_t)(tmp_%s >= 0 ? tmp_%s + 0.5 : tmp_%s - 0.5);"
                    s.Name
                    s.Name
                    s.Offset
                    s.Factor
                    s.Name
                    s.Name
                    s.Name
                    s.Name

            let computeRawFloat =
                sprintf
                    "    float tmp_%s = ((float)msg->%s - (float)%.17g) / (float)%.17g;\n    int64_t raw_%s = (int64_t)llroundf(tmp_%s);"
                    s.Name
                    s.Name
                    s.Offset
                    s.Factor
                    s.Name
                    s.Name

            let computeRaw =
                match config.PhysType.ToLowerInvariant() with
                | "fixed" ->
                    match Utils.tryPowerOfTenScale s.Factor with
                    | Some scale when abs (s.Offset - Math.Round(s.Offset)) < 1e-12 ->
                        sprintf
                            "    int64_t raw_%s = (int64_t)llround(((double)msg->%s - %.0f) * (double)%d);"
                            s.Name
                            s.Name
                            (Math.Round s.Offset)
                            scale
                    | _ ->
                        (match config.PhysMode.ToLowerInvariant() with
                         | "fixed_float" -> computeRawFloat
                         | _ -> computeRawDouble)
                | _ ->
                    (match config.PhysMode.ToLowerInvariant() with
                     | "float" -> computeRawFloat
                     | _ -> computeRawDouble)

            let setBits =
                sprintf "    %s(data, %d, %d, (uint64_t)raw_%s);" setFn startEff len s.Name

            [ match rangeChecks with
              | Some r -> yield r
              | None -> ()
              yield computeRaw
              yield setBits ]
            |> String.concat "\n"

        let private partitionMultiplex (message: Message) =
            let switchOpt =
                message.Signals |> List.tryFind (fun s -> s.MultiplexerIndicator = Some "M")

            let baseSignals =
                message.Signals |> List.filter (fun s -> s.MultiplexerIndicator.IsNone)

            let branches =
                message.Signals
                |> List.choose (fun s ->
                    match s.MultiplexerIndicator, s.MultiplexerSwitchValue with
                    | Some ind, Some v when ind = "m" -> Some(v, s)
                    | _ -> None)
                |> List.groupBy fst
                |> List.map (fun (k, xs) -> k, xs |> List.map snd)

            switchOpt, baseSignals, branches

        let generateMessageFiles (message: Message) (outputPath: string) (config: Signal.CANdy.Core.Config.Config) =
            let messageNameLower = message.Name.ToLowerInvariant()

            let messageHPath =
                Path.Combine(outputPath, "include", sprintf "%s.h" messageNameLower)

            let messageCPath = Path.Combine(outputPath, "src", sprintf "%s.c" messageNameLower)

            let banner =
                sprintf
                    "/* Generated by Signal CANdy\n   file_prefix=%s, phys_type=%s, phys_mode=%s, dispatch=%s, motorola_start_bit=%s */\n"
                    config.FilePrefix
                    config.PhysType
                    config.PhysMode
                    config.Dispatch
                    config.MotorolaStartBit

            let signalDeclarationsH =
                message.Signals |> List.map fieldDecl |> String.concat "\n"

            let switchOpt, baseSignals, branches = partitionMultiplex message

            let isMux =
                match switchOpt, branches with
                | Some _, _ :: _ -> true
                | _ -> false

            let useValidArray = isMux && message.Signals.Length > 64
            let validType, shiftSuffix, initLiteral =
                if useValidArray then
                    "uint8_t", "", ""
                elif isMux && message.Signals.Length > 32 then
                    "uint64_t", "1ULL", "0ULL"
                else
                    "uint32_t", "1u", "0u"

            let validArraySize =
                if useValidArray then
                    (message.Signals.Length + 7) / 8
                else
                    0

            let validMacro (sigName: string) =
                sprintf "%s_VALID_%s" (message.Name.ToUpperInvariant()) (sigName.ToUpperInvariant())

            let signalDecodeFor s =
                genDecodeForSignal s config.RangeCheck config

            let signalDecodeWithValid s =
                let body = signalDecodeFor s in

                if isMux then
                    body + (sprintf "\n    msg->valid |= %s;" (validMacro s.Name))
                else
                    body

            let signalDecodeC =
                match switchOpt, branches with
                | Some sw, (_ :: _) ->
                    let rawVar = sprintf "raw_%s" sw.Name

                    let swBlock =
                        let body = signalDecodeWithValid sw

                        body
                        + (sprintf "\n    msg->mux_active = (%s_mux_e)((int)%s);" message.Name rawVar)

                    let baseBlock =
                        baseSignals |> List.map signalDecodeWithValid |> String.concat "\n\n"

                    let branchesBlock =
                        branches
                        |> List.map (fun (k, sigs) ->
                            let inner = sigs |> List.map signalDecodeWithValid |> String.concat "\n\n"

                            [ sprintf "    if ((int)%s == %d) {" rawVar k; inner; "    }" ]
                            |> String.concat "\n")
                        |> String.concat "\n"

                    [ if isMux then
                          sprintf "    msg->valid = %s;" initLiteral
                      else
                          ""
                      swBlock
                      baseBlock
                      branchesBlock ]
                    |> List.filter (fun s -> not (String.IsNullOrWhiteSpace s))
                    |> String.concat "\n\n"
                | _ -> message.Signals |> List.map signalDecodeFor |> String.concat "\n\n"

            let signalEncodeC =
                match switchOpt, branches with
                | Some sw, (_ :: _) ->
                    let len = int sw.Length
                    let startEff = Utils.chooseStartBit sw config
                    let (_, setFn) = Utils.accessorNames sw.ByteOrder

                    let rangeChecks =
                        if config.RangeCheck then
                            match sw.Minimum, sw.Maximum with
                            | Some minV, Some maxV ->
                                if minV >= maxV then
                                    None
                                elif Utils.isRawRangeSentinel minV maxV sw.Factor sw.Offset sw.Length sw.IsSigned then
                                    None
                                else
                                    Some(
                                        sprintf
                                            "    if (msg->%s < %.17g || msg->%s > %.17g) { return false; }"
                                            sw.Name
                                            minV
                                            sw.Name
                                            maxV
                                    )
                            | Some minV, None -> Some(sprintf "    if (msg->%s < %.17g) { return false; }" sw.Name minV)
                            | None, Some maxV -> Some(sprintf "    if (msg->%s > %.17g) { return false; }" sw.Name maxV)
                            | _ -> None
                        else
                            None

                    let computeRawDouble =
                        sprintf
                            "    double tmp_%s = ((double)msg->%s - %.17g) / %.17g;\n    int64_t raw_%s = (int64_t)(tmp_%s >= 0 ? tmp_%s + 0.5 : tmp_%s - 0.5);"
                            sw.Name
                            sw.Name
                            sw.Offset
                            sw.Factor
                            sw.Name
                            sw.Name
                            sw.Name
                            sw.Name

                    let computeRawFloat =
                        sprintf
                            "    float tmp_%s = ((float)msg->%s - (float)%.17g) / (float)%.17g;\n    int64_t raw_%s = (int64_t)llroundf(tmp_%s);"
                            sw.Name
                            sw.Name
                            sw.Offset
                            sw.Factor
                            sw.Name
                            sw.Name

                    let computeRaw =
                        match config.PhysType.ToLowerInvariant() with
                        | "fixed" ->
                            match Utils.tryPowerOfTenScale sw.Factor with
                            | Some scale when abs (sw.Offset - Math.Round(sw.Offset)) < 1e-12 ->
                                sprintf
                                    "    int64_t raw_%s = (int64_t)llround(((double)msg->%s - %.0f) * (double)%d);"
                                    sw.Name
                                    sw.Name
                                    (Math.Round sw.Offset)
                                    scale
                            | _ ->
                                (match config.PhysMode.ToLowerInvariant() with
                                 | "fixed_float" -> computeRawFloat
                                 | _ -> computeRawDouble)
                        | _ ->
                            (match config.PhysMode.ToLowerInvariant() with
                             | "float" -> computeRawFloat
                             | _ -> computeRawDouble)

                    let setBits =
                        sprintf "    %s(data, %d, %d, (uint64_t)raw_%s);" setFn startEff len sw.Name

                    let baseBlock =
                        baseSignals
                        |> List.map (fun s -> genEncodeForSignal s config.RangeCheck config)
                        |> String.concat "\n\n"

                    let branchesBlock =
                        branches
                        |> List.map (fun (k, sigs) ->
                            let inner =
                                sigs
                                |> List.map (fun s -> genEncodeForSignal s config.RangeCheck config)
                                |> String.concat "\n\n"

                            [ sprintf "    if ((int)raw_%s == %d) {" sw.Name k; inner; "    }" ]
                            |> String.concat "\n")
                        |> String.concat "\n"

                    [ match rangeChecks with
                      | Some r -> yield r
                      | None -> ()
                      yield computeRaw
                      yield setBits
                      yield baseBlock
                      yield branchesBlock ]
                    |> List.filter (fun s -> not (String.IsNullOrWhiteSpace s))
                    |> String.concat "\n\n"
                | _ ->
                    message.Signals
                    |> List.map (fun s -> genEncodeForSignal s config.RangeCheck config)
                    |> String.concat "\n\n"

            let valueTableDeclarations =
                let lines = System.Collections.Generic.List<string>()

                let vtSignals =
                    message.Signals
                    |> List.choose (fun s -> s.ValueTable |> Option.map (fun vt -> s, vt))

                vtSignals
                |> List.iter (fun (s, vt) ->
                    let enumName = sprintf "%s_%s_e" message.Name s.Name
                    lines.Add("typedef enum {")
                    let mutable used = Set.empty

                    vt
                    |> List.iter (fun (v, name) ->
                        let baseLabel = sanitizeEnumIdent name

                        let rec uniqueLabel lbl idx =
                            let candidate = if idx = 0 then lbl else sprintf "%s_%d" lbl idx

                            if used.Contains candidate then
                                uniqueLabel lbl (idx + 1)
                            else
                                candidate

                        let label = uniqueLabel baseLabel 0
                        used <- used.Add label

                        lines.Add(
                            sprintf
                                "    %s_%s_%s = %d,"
                                (message.Name.ToUpperInvariant())
                                (s.Name.ToUpperInvariant())
                                label
                                v
                        ))

                    lines.Add(sprintf "} %s;" enumName)
                    lines.Add ""
                    lines.Add(sprintf "const char* %s_%s_to_string(int v);" message.Name s.Name)
                    lines.Add "")

                String.concat "\n" (List.ofSeq lines)

            let muxPreambleDeclarations, muxStructFields =
                let preambleLines = System.Collections.Generic.List<string>()
                let structFieldLines = System.Collections.Generic.List<string>()
                let switchOpt2, _, branches2 = partitionMultiplex message

                let isMux2 =
                    match switchOpt2, branches2 with
                    | Some _, _ :: _ -> true
                    | _ -> false

                if isMux2 then
                    let enumName = sprintf "%s_mux_e" message.Name
                    preambleLines.Add(sprintf "typedef enum { ")

                    let enumEntries =
                        branches2
                        |> List.map (fun (k, _) -> sprintf "    %s_MUX_%d = %d" (message.Name.ToUpperInvariant()) k k)
                        |> String.concat ",\n"

                    preambleLines.Add enumEntries
                    preambleLines.Add(sprintf "} %s;" enumName)
                    preambleLines.Add ""

                    message.Signals
                    |> List.iteri (fun idx s ->
                        preambleLines.Add(
                            sprintf
                                "#define %s (%s << %d)"
                                (sprintf "%s_VALID_%s" (message.Name.ToUpperInvariant()) (s.Name.ToUpperInvariant()))
                                shiftSuffix
                                idx
                        ))

                    preambleLines.Add ""

                    structFieldLines.Add(sprintf "    %s valid;" validType)

                    if validType = "uint64_t" then
                        structFieldLines.Add("    /* valid field widened to uint64_t: signal count > 32 */")
                        structFieldLines.Add("    /* decode init literal: = 0ULL; */")

                    structFieldLines.Add(sprintf "    %s_mux_e mux_active;" message.Name)

                String.concat "\n" (List.ofSeq preambleLines), String.concat "\n" (List.ofSeq structFieldLines)

            let preStructDeclarations =
                [ valueTableDeclarations; muxPreambleDeclarations ]
                |> List.filter (fun block -> not (String.IsNullOrWhiteSpace block))
                |> String.concat "\n"

            let valueTableDefinitions =
                let lines = System.Collections.Generic.List<string>()

                let vtSignals =
                    message.Signals
                    |> List.choose (fun s -> s.ValueTable |> Option.map (fun vt -> s, vt))

                vtSignals
                |> List.iter (fun (s, vt) ->
                    lines.Add(sprintf "const char* %s_%s_to_string(int v) {" message.Name s.Name)
                    lines.Add "    switch (v) {"

                    vt
                    |> List.iter (fun (v, name) ->
                        lines.Add(sprintf "    case %d: return \"%s\";" v (name.Replace("\"", "\\\""))))

                    lines.Add "    default: return \"UNKNOWN\";"
                    lines.Add "    }"
                    lines.Add "}"
                    lines.Add "")

                String.concat "\n" (List.ofSeq lines)

            let crcSignalOpt = message.Signals |> List.tryFind (fun s -> s.CrcMeta.IsSome)

            let counterSignalOpt =
                message.Signals |> List.tryFind (fun s -> s.CounterMeta.IsSome)

            let hasCounter = counterSignalOpt.IsSome

            let counterStateTypeDecl =
                if hasCounter then
                    sprintf
                        "typedef struct { uint8_t last_counter; bool initialized; } %s_counter_state_t;"
                        message.Name
                else
                    ""

            let counterCheckFuncDecl =
                if hasCounter then
                    sprintf
                        "bool %s_check_counter(%s_counter_state_t* state, const %s_t* msg);"
                        message.Name
                        message.Name
                        message.Name
                else
                    ""

            let crcDecodeCheck =
                match crcSignalOpt with
                | Some crcSig when crcSig.CrcMeta.Value.Params.Width = 8 ->
                    let meta = crcSig.CrcMeta.Value

                    let funcName =
                        match meta.Algorithm with
                        | CrcAlgorithmId.CRC8_SAE_J1850 -> "sc_crc8_sae_j1850"
                        | CrcAlgorithmId.CRC8_8H2F -> "sc_crc8_8h2f"
                        | CrcAlgorithmId.Custom name -> sprintf "sc_crc8_%s" (name.ToLowerInvariant().Replace("-", "_"))
                        | _ -> "sc_crc8_unknown"

                    let byteCount = meta.ByteRange.End - meta.ByteRange.Start + 1

                    match message.CrcCounterMode with
                    | Some CrcCounterMode.Validate ->
                        sprintf
                            "    if (%s(&data[%d], %d) != (uint8_t)msg->%s) { return false; }"
                            funcName
                            meta.ByteRange.Start
                            byteCount
                            crcSig.Name
                    | _ -> ""
                | _ -> ""

            let crcEncodeInsert =
                match crcSignalOpt with
                | Some crcSig when crcSig.CrcMeta.Value.Params.Width = 8 ->
                    let meta = crcSig.CrcMeta.Value

                    let funcName =
                        match meta.Algorithm with
                        | CrcAlgorithmId.CRC8_SAE_J1850 -> "sc_crc8_sae_j1850"
                        | CrcAlgorithmId.CRC8_8H2F -> "sc_crc8_8h2f"
                        | CrcAlgorithmId.Custom name -> sprintf "sc_crc8_%s" (name.ToLowerInvariant().Replace("-", "_"))
                        | _ -> "sc_crc8_unknown"

                    let byteCount = meta.ByteRange.End - meta.ByteRange.Start + 1
                    let startEff = chooseStartBit crcSig config
                    let (_, setFn) = accessorNames crcSig.ByteOrder

                    match message.CrcCounterMode with
                    | Some CrcCounterMode.Validate ->
                        sprintf
                            "    uint8_t crc_val_%s = %s(&data[%d], %d);\n    %s(data, %d, %d, (uint64_t)crc_val_%s);"
                            crcSig.Name
                            funcName
                            meta.ByteRange.Start
                            byteCount
                            setFn
                            startEff
                            (int crcSig.Length)
                            crcSig.Name
                    | _ -> ""
                | _ -> ""

            let counterCheckFuncImpl =
                match counterSignalOpt with
                | Some counterSig ->
                    let meta = counterSig.CounterMeta.Value

                    sprintf
                        "bool %s_check_counter(%s_counter_state_t* state, const %s_t* msg) {\n    if (!state->initialized) { state->last_counter = (uint8_t)msg->%s; state->initialized = true; return true; }\n    uint8_t expected = (uint8_t)((state->last_counter + 1) %% %d);\n    state->last_counter = (uint8_t)msg->%s;\n    return (uint8_t)msg->%s == expected;\n}"
                        message.Name
                        message.Name
                        message.Name
                        counterSig.Name
                        meta.Modulus
                        counterSig.Name
                        counterSig.Name
                | None -> ""

            let headerContent =
                let model: (string * obj) list =
                    [ "banner", box banner
                      "header_guard", box (sprintf "%s_H" (message.Name.ToUpperInvariant()))
                      "pre_struct_declarations", box preStructDeclarations
                      "struct_extra_fields", box muxStructFields
                      "signal_declarations_h", box signalDeclarationsH
                      "message_name", box message.Name
                      "has_counter", box hasCounter
                      "counter_state_type_decl", box counterStateTypeDecl
                      "counter_check_func_decl", box counterCheckFuncDecl ]

                Templates.renderOrRaise "message.h.scriban" model

            let sourceContent =
                let model: (string * obj) list =
                    [ "banner", box banner
                      "message_header_name", box (sprintf "%s.h" messageNameLower)
                      "utils_header_name", box (Utils.utilsHeaderName config)
                      "value_table_definitions", box valueTableDefinitions
                      "message_name", box message.Name
                      "message_length", box (int message.Length)
                      "signal_decode_c", box signalDecodeC
                      "signal_encode_c", box signalEncodeC
                      "crc_decode_check", box crcDecodeCheck
                      "crc_encode_insert", box crcEncodeInsert
                      "has_counter", box hasCounter
                      "counter_check_func_impl", box counterCheckFuncImpl ]

                Templates.renderOrRaise "message.c.scriban" model

            File.WriteAllText(messageHPath, headerContent)
            File.WriteAllText(messageCPath, sourceContent)
            messageHPath, messageCPath

    module Registry =
        type private RegistryHeaderTemplateModel =
            { banner: string
              header_guard: string
              registry_declaration: string }

        type private RegistrySourceTemplateModel =
            { banner: string
              registry_header_name: string
              message_includes: string
              registry_body: string }

        let generateRegistryFiles (ir: Ir) (outputPath: string) (config: Signal.CANdy.Core.Config.Config) =
            let regHName = sprintf "%sregistry.h" config.FilePrefix
            let regCName = sprintf "%sregistry.c" config.FilePrefix
            let registryHPath = Path.Combine(outputPath, "include", regHName)
            let registryCPath = Path.Combine(outputPath, "src", regCName)

            let guard =
                (config.FilePrefix + "registry_h").ToUpperInvariant()
                |> Seq.map (fun ch -> if Char.IsLetterOrDigit ch then ch else '_')
                |> Seq.toArray
                |> fun arr -> new string (arr)

            let banner =
                sprintf
                    "/* Generated by Signal CANdy\n   file_prefix=%s, phys_type=%s, phys_mode=%s, dispatch=%s, motorola_start_bit=%s */\n"
                    config.FilePrefix
                    config.PhysType
                    config.PhysMode
                    config.Dispatch
                    config.MotorolaStartBit

            let registryHContent =
                let model: (string * obj) list =
                    [ "banner", box banner
                      "header_guard", box guard
                      "registry_declaration",
                      box "bool decode_message(uint32_t id, const uint8_t data[], uint8_t dlc, void* msg);" ]

                Templates.renderOrRaise "registry.h.scriban" model

            File.WriteAllText(registryHPath, registryHContent)

            let includes =
                ir.Messages
                |> List.map (fun m -> sprintf "#include \"%s.h\"" (m.Name.ToLowerInvariant()))
                |> String.concat "\n"

            let body =
                if config.Dispatch.ToLowerInvariant() = "direct_map" then
                    let cases =
                        ir.Messages
                        |> List.map (fun m ->
                            sprintf
                                "        case %du: return %s_decode((%s_t*)msg, data, dlc);"
                                (int m.Id)
                                m.Name
                                m.Name)
                        |> String.concat "\n"

                    sprintf
                        "bool decode_message(uint32_t id, const uint8_t data[], uint8_t dlc, void* msg) {\n    switch (id) {\n%s\n        default: return false;\n    }\n}"
                        cases
                else
                    let sorted = ir.Messages |> List.sortBy (fun m -> m.Id)

                    let entries =
                        sorted
                        |> List.map (fun m -> sprintf "    { %du, (decode_func_t)%s_decode }" (int m.Id) m.Name)
                        |> String.concat ",\n"

                    let table =
                        [ "typedef bool (*decode_func_t)(void* msg, const uint8_t data[], uint8_t dlc);"
                          ""
                          "typedef struct { uint32_t id; decode_func_t func; } decoder_entry_t;"
                          ""
                          "static const decoder_entry_t decoders[] = {"
                          entries
                          "};"
                          "" ]
                        |> String.concat "\n"

                    let search =
                        [ "bool decode_message(uint32_t id, const uint8_t data[], uint8_t dlc, void* msg) {"
                          "    int low = 0;"
                          "    int high = (int)(sizeof(decoders) / sizeof(decoder_entry_t)) - 1;"
                          "    while (low <= high) {"
                          "        int mid = low + (high - low) / 2;"
                          "        if (decoders[mid].id == id) {"
                          "            return decoders[mid].func(msg, data, dlc);"
                          "        }"
                          "        if (decoders[mid].id < id) low = mid + 1; else high = mid - 1;"
                          "    }"
                          "    return false;"
                          "}"
                          "" ]
                        |> String.concat "\n"

                    table + search

            let finalC =
                let model: (string * obj) list =
                    [ "banner", box banner
                      "registry_header_name", box (sprintf "%sregistry.h" config.FilePrefix)
                      "message_includes", box includes
                      "registry_body", box body ]

                Templates.renderOrRaise "registry.c.scriban" model

            File.WriteAllText(registryCPath, finalC)
            registryHPath, registryCPath

    // Compatibility shims for legacy includes (utils.h, registry.h)
    let private shimHeader (name: string) (target: string) =
        let guard = (name.Replace('.', '_') + "_SHIM").ToUpperInvariant()

        "#ifndef "
        + guard
        + "\n#define "
        + guard
        + "\n\n"
        + "#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n"
        + "#include \""
        + target
        + "\"\n\n"
        + "#ifdef __cplusplus\n}\n#endif\n\n"
        + "#endif // "
        + guard

    // Main entry: generate code and return file lists
    let generate
        (ir: Ir)
        (outputPath: string)
        (config: Signal.CANdy.Core.Config.Config)
        : Result<GeneratedFiles, CodeGenError> =
        try
            // Ensure output directories
            Directory.CreateDirectory(Path.Combine(outputPath, "include")) |> ignore

            Directory.CreateDirectory(Path.Combine(outputPath, "src")) |> ignore

            let overflowGuard =
                ir.Messages
                |> List.tryFind (fun msg ->
                    let hasMuxSwitch =
                        msg.Signals |> List.exists (fun s -> s.MultiplexerIndicator = Some "M")

                    let hasMuxBranches =
                        msg.Signals
                        |> List.exists (fun s -> s.MultiplexerIndicator = Some "m" && s.MultiplexerSwitchValue.IsSome)

                    hasMuxSwitch && hasMuxBranches && msg.Signals.Length > 64)

            match overflowGuard with
            | Some msg ->
                Error(
                    CodeGenError.UnsupportedFeature(
                        sprintf
                            "Message '%s' has %d signals (>64); valid bitmask cannot be represented in 64 bits."
                            msg.Name
                            msg.Signals.Length
                    )
                )
            | None ->
                let ir = Signal.CANdy.Core.Dbc.applyConfigMetadata (Some config) ir

                let hasCrcValidateMode =
                    match config.CrcCounter with
                    | Some crcCfg when crcCfg.Mode = "validate" -> true
                    | _ -> false

                let crcCounterGuard =
                    match config.CrcCounter with
                    | Some crcCfg when crcCfg.Mode = "fail_fast" ->
                        if crcCfg.Messages.IsEmpty then
                            None
                        else
                            let firstMsg = crcCfg.Messages |> Map.toList |> List.head |> fst
                            Some(firstMsg, "CRC/counter", None)
                    | Some _ -> None
                    | None ->
                        if config.CrcCounterCheck then
                            ir.Messages
                            |> List.tryPick (fun msg ->
                                msg.Signals
                                |> List.tryFind (fun s -> s.IsCrc || s.IsCounter)
                                |> Option.map (fun s ->
                                    (msg.Name,
                                     (if s.IsCrc then "CRC"
                                      elif s.IsCounter then "counter"
                                      else "CRC/counter"),
                                     Some s.Name)))
                        else
                            None

                match crcCounterGuard with
                | Some(msgName, kind, signalNameOpt) ->
                    let signalInfo =
                        match signalNameOpt with
                        | Some signalName -> sprintf ", signal '%s'" signalName
                        | None -> ""

                    Error(
                        CodeGenError.UnsupportedFeature(
                            sprintf
                                "crc_counter_check=true: CRC/counter signal in message '%s' (%s%s) is not supported in the current configuration. Use crc_counter.mode=validate for explicit CRC validation."
                                msgName
                                kind
                                signalInfo
                        )
                    )
                | None ->
                    let hasAnyCrcMeta =
                        ir.Messages
                        |> List.exists (fun msg -> msg.Signals |> List.exists (fun s -> s.CrcMeta.IsSome))

                    let crcWidthError =
                        if hasCrcValidateMode || hasAnyCrcMeta then
                            ir.Messages
                            |> List.tryPick (fun msg ->
                                msg.Signals
                                |> List.tryPick (fun s ->
                                    match s.CrcMeta with
                                    | Some meta when meta.Params.Width <> 8 ->
                                        Some(
                                            sprintf
                                                "CRC signal '%s' in message '%s' has unsupported width %d (only CRC-8 is supported in this version)."
                                                s.Name
                                                msg.Name
                                                meta.Params.Width
                                        )
                                    | _ -> None))
                        else
                            None

                    match crcWidthError with
                    | Some errMsg -> Error(CodeGenError.UnsupportedFeature errMsg)
                    | None ->

                        // Clean stale prefixed common files
                        let keepUtilsH = Utils.utilsHeaderName config
                        let keepUtilsC = Utils.utilsSourceName config
                        let keepRegH = sprintf "%sregistry.h" config.FilePrefix
                        let keepRegC = sprintf "%sregistry.c" config.FilePrefix
                        let includeDir = Path.Combine(outputPath, "include")
                        let srcDir = Path.Combine(outputPath, "src")

                        if Directory.Exists includeDir then
                            Directory.GetFiles(includeDir, "*utils.h")
                            |> Array.iter (fun f ->
                                if Path.GetFileName(f) <> keepUtilsH then
                                    try
                                        File.Delete f
                                    with _ ->
                                        ())

                            Directory.GetFiles(includeDir, "*registry.h")
                            |> Array.iter (fun f ->
                                if Path.GetFileName(f) <> keepRegH then
                                    try
                                        File.Delete f
                                    with _ ->
                                        ())

                        if Directory.Exists srcDir then
                            Directory.GetFiles(srcDir, "*utils.c")
                            |> Array.iter (fun f ->
                                if Path.GetFileName(f) <> keepUtilsC then
                                    try
                                        File.Delete f
                                    with _ ->
                                        ())

                            Directory.GetFiles(srcDir, "*registry.c")
                            |> Array.iter (fun f ->
                                if Path.GetFileName(f) <> keepRegC then
                                    try
                                        File.Delete f
                                    with _ ->
                                        ())

                        // Generate utils
                        let uH = Utils.utilsHeaderName config
                        let uC = Utils.utilsSourceName config
                        let uHPath = Path.Combine(outputPath, "include", uH)
                        let uCPath = Path.Combine(outputPath, "src", uC)
                        File.WriteAllText(uHPath, Utils.utilsHContent config ir)
                        File.WriteAllText(uCPath, Utils.utilsCContent config ir)

                        // Emit compatibility shims
                        let shimUtilsPath = Path.Combine(outputPath, "include", "utils.h")
                        let shimRegPath = Path.Combine(outputPath, "include", "registry.h")
                        File.WriteAllText(shimUtilsPath, shimHeader "utils.h" uH)
                        File.WriteAllText(shimRegPath, shimHeader "registry.h" keepRegH)

                        // Messages
                        let msgFiles =
                            ir.Messages
                            |> List.map (fun m -> Message.generateMessageFiles m outputPath config)
                        // Registry
                        let regHPath, regCPath = Registry.generateRegistryFiles ir outputPath config

                        let sources = msgFiles |> List.map snd |> (fun xs -> uCPath :: regCPath :: xs)

                        let headers =
                            msgFiles
                            |> List.map fst
                            |> fun xs -> uHPath :: regHPath :: shimUtilsPath :: shimRegPath :: xs

                        let others: string list = []

                        Ok
                            { Sources = sources
                              Headers = headers
                              Others = others }
        with
        | TemplateRenderException msg -> Error(CodeGenError.TemplateError msg)
        | ex -> Error(CodeGenError.Unknown(sprintf "Codegen exception: %s" ex.Message))
