namespace Generator

open System.IO
open Generator.Ir
open Generator.Config

module Registry =

    let generateRegistryFiles (ir: Ir) (outputPath: string) (config: Generator.Config.Config) =
        let regHName = sprintf "%sregistry.h" config.FilePrefix
        let regCName = sprintf "%sregistry.c" config.FilePrefix
        let registryHPath = Path.Combine(outputPath, "include", regHName)
        let registryCPath = Path.Combine(outputPath, "src", regCName)

        let guard =
            (config.FilePrefix + "registry_h").ToUpperInvariant()
            |> Seq.map (fun ch -> if System.Char.IsLetterOrDigit ch then ch else '_')
            |> Seq.toArray
            |> fun arr -> new string(arr)
        let banner = sprintf "/* Generated by Signal CANdy\n   file_prefix=%s, phys_type=%s, phys_mode=%s, dispatch=%s, motorola_start_bit=%s */\n" config.FilePrefix config.PhysType config.PhysMode config.Dispatch config.MotorolaStartBit
        let registryHContent =
            banner + sprintf "#ifndef %s\n#define %s\n\n#include <stdint.h>\n#include <stdbool.h>\n\n#ifdef __cplusplus\nextern \"C\" {\n#endif\n\nbool decode_message(uint32_t id, const uint8_t data[], uint8_t dlc, void* msg);\n\n#ifdef __cplusplus\n}\n#endif\n\n#endif // %s" guard guard guard
        File.WriteAllText(registryHPath, registryHContent)

        let includes =
            ir.Messages
            |> List.map (fun m -> sprintf "#include \"%s.h\"" (m.Name.ToLowerInvariant()))
            |> String.concat "\n"

        let body =
            if config.Dispatch.ToLowerInvariant() = "direct_map" then
                let cases =
                    ir.Messages
                    |> List.map (fun m ->
                        sprintf "        case %du: return %s_decode((%s_t*)msg, data, dlc);" (int m.Id) m.Name m.Name)
                    |> String.concat "\n"
                sprintf "bool decode_message(uint32_t id, const uint8_t data[], uint8_t dlc, void* msg) {\n    switch (id) {\n%s\n        default: return false;\n    }\n}" cases
            else
                let sorted = ir.Messages |> List.sortBy (fun m -> m.Id)
                let entries =
                    sorted
                    |> List.map (fun m -> sprintf "    { %du, (decode_func_t)%s_decode }" (int m.Id) m.Name)
                    |> String.concat ",\n"
                let table =
                    sprintf "typedef bool (*decode_func_t)(void* msg, const uint8_t data[], uint8_t dlc);\n\ntypedef struct { uint32_t id; decode_func_t func; } decoder_entry_t;\n\nstatic const decoder_entry_t decoders[] = {\n%s\n};\n" entries
                let search =
                    "bool decode_message(uint32_t id, const uint8_t data[], uint8_t dlc, void* msg) {\n    int low = 0;\n    int high = (int)(sizeof(decoders) / sizeof(decoder_entry_t)) - 1;\n    while (low <= high) {\n        int mid = low + (high - low) / 2;\n        if (decoders[mid].id == id) {\n            return decoders[mid].func(msg, data, dlc);\n        }\n        if (decoders[mid].id < id) low = mid + 1; else high = mid - 1;\n    }\n    return false;\n}\n"
                table + search
        let finalC = banner + "#include <stdint.h>\n#include <stdbool.h>\n#include \"" + regHName + "\"\n" + includes + "\n\n" + body
        File.WriteAllText(registryCPath, finalC)
        ()