name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build & Test (Release)
        run: |
          dotnet restore
          dotnet build --configuration Release --nologo
          dotnet test --configuration Release -v minimal --nologo

      - name: Generate artifacts (optional)
        run: |
          dotnet run --project src/Generator -- --dbc examples/sample.dbc --out gen --config examples/config.yaml

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
